export const PARAMETER_CATEGORIES = [
    {
      id: "fisika",
      title: "Fisika",
      items: [
        { name: "Suhu*", price: "10.000", metode: "Termometer" },
        { name: "Rasa", price: "9.000", metode: "Organoleptik" },
        { name: "Bau", price: "9.000", metode: "Organoleptik" },
        { name: "Bau", price: "30.000", metode: "Spektrofotometri" },
        { name: "Warna", price: "9.000", metode: "Organoleptik" },
        { name: "Warna", price: "30.000", metode: "Spektrofotometri" },
        { name: "Kekeruhan", price: "15.000", metode: "Turbidimeter" },
        { name: "Benda terapung", price: "5.000", metode: "Visual" },
        { name: "Daya Hantar Listrik (DHL)*", price: "15.000", metode: "Ion selektif elektroda" },
        { name: "Lapisan minyak", price: "10.000", metode: "Visual" },
        { name: "Zat Padat Tersuspensi (TSS)*", price: "35.000", metode: "Gravimetri" },
        { name: "Zat Padat Terlarut (TDS)*", price: "25.000", metode: "Gravimetri" },
        { name: "Kecerahan", price: "12.000", metode: "Secchi Disc" },
        { name: "ORP", price: "15.000", metode: "Ion selektif elektroda" },
        { name: "Sampah", price: "5.000", metode: "Visual" },
        { name: "Total Solid", price: "65.000", metode: "Gravimetri" },
        { name: "Salinitas", price: "20.000", metode: "Ion selektif elektroda" },
        { name: "Kedalaman", price: "15.000", metode: "Pengukuran langsung" },
        { name: "Debit", price: "150.000", metode: "Pengukuran langsung" },
      ],
    },
    {
      id: "kimia-anorganik",
      title: "Kimia Anorganik",
      items: [
        { name: "pH*", price: "15.000", metode: "Ion selektif elektroda" },
        { name: "Oksigen terlarut (DO)*", price: "15.000", metode: "Titrasi" },
        { name: "BOD*", price: "60.000", metode: "Titrasi" },
        { name: "COD*", price: "65.000", metode: "Spektrofotometri" },
        { name: "Orto Fosfat sebagai P atau PO4", price: "55.000", metode: "Spektrofotometri" },
        { name: "Nitrat sebagai NO3 atau N*", price: "40.000", metode: "Spektrofotometri" },
        { name: "Nitrat sebagai NO3 atau N* (kit)", price: "90.000", metode: "Spektrofotometri (kit)" },
        { name: "Nitrit sebagai NO2 atau N*", price: "40.000", metode: "Spektrofotometri" },
        { name: "Ammoniak sebagai N atau NH3*", price: "55.000", metode: "Spektrofotometri" },
        { name: "Klorida - Cl*", price: "38.000", metode: "Titrasi" },
        { name: "Sianida - CN", price: "55.000", metode: "Spektrofotometri" },
        { name: "Sulfat - SO4*", price: "40.000", metode: "Spektrofotometri" },
        { name: "Aluminium (Al)", price: "75.000", metode: "AAS" },
        { name: "Aluminium (Al)", price: "120.000", metode: "AAS-GF" },
        { name: "Arsen (As)", price: "75.000", metode: "AAS" },
        { name: "Arsen (As)", price: "120.000", metode: "AAS-GF" },
        { name: "Zinc (Zn)", price: "75.000", metode: "AAS" },
        { name: "Zinc (Zn)", price: "120.000", metode: "AAS-GF" },
        { name: "Tembaga (Cu)", price: "75.000", metode: "AAS" },
        { name: "Tembaga (Cu)", price: "120.000", metode: "AAS-GF" },
        { name: "Nikel (Ni)", price: "75.000", metode: "AAS" },
        { name: "Nikel (Ni)", price: "120.000", metode: "AAS-GF" },
        { name: "Timbal (Pb)", price: "75.000", metode: "AAS" },
        { name: "Timbal (Pb)", price: "160.000", metode: "AAS-GF" },
        { name: "Barium (Ba)", price: "75.000", metode: "AAS" },
        { name: "Barium (Ba)", price: "120.000", metode: "AAS-GF" },
        { name: "Besi (Fe)", price: "75.000", metode: "AAS" },
        { name: "Besi (Fe)", price: "120.000", metode: "AAS-GF" },
        { name: "Cadmium (Cd)", price: "75.000", metode: "AAS" },
        { name: "Cadmium (Cd)", price: "160.000", metode: "AAS-GF" },
        { name: "Kobalt (Co)", price: "75.000", metode: "AAS" },
        { name: "Kobalt (Co)", price: "160.000", metode: "AAS-GF" },
        { name: "Kromium Total (Cr)", price: "75.000", metode: "AAS" },
        { name: "Kromium Total (Cr)", price: "160.000", metode: "AAS-GF" },
        { name: "Kromium valensi (VI)", price: "75.000", metode: "AAS" },
        { name: "Mangan (Mn)", price: "75.000", metode: "AAS" },
        { name: "Mangan (Mn)", price: "90.000", metode: "AAS-GF" },
        { name: "Natrium (Na)", price: "75.000", metode: "AAS" },
        { name: "Perak (Ag)", price: "75.000", metode: "AAS" },
        { name: "Perak (Ag)", price: "160.000", metode: "AAS-GF" },
        { name: "Air Raksa (Hg)", price: "125.000", metode: "AAS-cold vapour" },
        { name: "Selenium (Se)", price: "75.000", metode: "AAS" },
        { name: "Selenium (Se)", price: "180.000", metode: "AAS-GF" },
        { name: "Kalsium (Ca)", price: "75.000", metode: "AAS" },
        { name: "Kalsium (Ca)", price: "28.000", metode: "Titrasi" },
        { name: "Silika (Si)", price: "55.000", metode: "Spektrofotometri" },
        { name: "Silika (Si)", price: "75.000", metode: "AAS" },
        { name: "Magnesium (Mg)", price: "75.000", metode: "AAS" },
        { name: "Magnesium (Mg)", price: "30.000", metode: "Titrasi" },
        { name: "Litium (Li)", price: "75.000", metode: "AAS" },
        { name: "Litium (Li)", price: "160.000", metode: "AAS-GF" },
        { name: "Kalium (K)", price: "75.000", metode: "AAS" },
        { name: "Boron (B)", price: "75.000", metode: "AAS" },
        { name: "Boron (B)", price: "120.000", metode: "AAS-GF" },
        { name: "Bromium (Br)", price: "75.000", metode: "Spektrofotometri" },
        { name: "Bromium (Br)", price: "120.000", metode: "AAS-GF" },
        { name: "Total Posfat*", price: "55.000", metode: "Spektrofotometri" },
        { name: "Fluorida-F", price: "50.000", metode: "Spektrofotometri" },
        { name: "Kesadahan sebagai CaCO3", price: "38.000", metode: "Titrasi" },
        { name: "Alkalinitas total", price: "30.000", metode: "Titrasi" },
        { name: "Asiditas", price: "25.000", metode: "Titrasi" },
        { name: "Klorin bebas", price: "25.000", metode: "Spektrofotometri" },
        { name: "Total klorin", price: "35.000", metode: "Spektrofotometri" },
        { name: "Total Nitrogen", price: "65.000", metode: "Spektrofotometri" },
        { name: "Amoniak bebas", price: "80.000", metode: "Perhitungan" },
        { name: "Sianida (CN)", price: "68.000", metode: "Spektrofotometri" },
      ],
    },
    {
      id: "kimia-organik",
      title: "Kimia Organik",
      items: [
        { name: "Karbondioksida (CO2)", price: "25.000", metode: "Titrasi" },
        { name: "Sulfida sebagai H2S", price: "55.000", metode: "Spektrofotometri" },
        { name: "Sulfit (SO3)", price: "40.000", metode: "Titrasi" },
        { name: "Iodium", price: "48.000", metode: "Spektrofotometri" },
        { name: "Salinitas", price: "80.000", metode: "Titrasi" },
        { name: "Fenol", price: "120.000", metode: "Spektrofotometri" },
        { name: "Minyak dan Lemak", price: "125.000", metode: "Gravimetri" },
        { name: "Detergen / surfaktan anionik (MBAS)*", price: "60.000", metode: "Spektrofotometri" },
        { name: "Total Organik Carbon (TOC)", price: "300.000", metode: "Spektrofotometri" },
        { name: "Total Organik Carbon (TOC)", price: "320.000", metode: "Analyzer UV" },
        { name: "Klorofil a", price: "76.000", metode: "Spektrofotometri" },
        { name: "Senyawa Fenol", price: "200.000", metode: "GCMS" },
        { name: "Angka (KMnO4)", price: "20.000", metode: "Titrasi" },
        { name: "Golongan organofosfat", price: "550.000", metode: "Kuantitatif GCMS" },
        { name: "Golongan karbamat", price: "550.000", metode: "Kuantitatif GCMS" },
        { name: "Golongan organoklorin", price: "550.000", metode: "Kuantitatif GCMS" },
        { name: "Golongan Pestisida lainnya", price: "550.000", metode: "Kuantitatif GCMS" },
      ],
    },
    {
      id: "mikrobiologi",
      title: "Mikrobiologi",
      items: [
        { name: "Total Coli", price: "85.000", metode: "CFU" },
        { name: "Total Coli", price: "85.000", metode: "MPN" },
        { name: "Fecal Coli", price: "85.000", metode: "CFU" },
        { name: "Fecal Coli", price: "85.000", metode: "MPN" },
        { name: "E. coli", price: "85.000", metode: "CFU" },
        { name: "E. coli", price: "85.000", metode: "MPN" },
      ],
    },
  ];

export const SAMPLING_TARIFFS = [
    { label: "Dalam Kota Padang", price: "475.000" },
    { label: "Luar kota > 50–100 km ke lokasi", price: "950.000" },
    { label: "Luar kota > 100–200 km ke lokasi", price: "1.850.000" },
    { label: "Luar kota > 200 km ke lokasi", price: "2.950.000" },
  ];
